-- 2.Create INSERT script for adding above provide data into. 

--  INSERT INTO table

-- Syntax


INSERT INTO `Loans`(
`ID` ,
`First Name` ,
`Last Name`,
`Email`,
`Loan Amount`,
`Purpose`,
`Status` 
) VALUES (
'1',
'John',
'Doe',
'john.doe@example.com',
'10000',
'Home Improvement',
'Approved'
);

-- This way we can INSERT data into table.
-- If we want more data in the table we have to change the values in the above syntax.

